aws:
  accountId: "<aws account>"
  region: us-west-2

tenantId: ""
environment: "dev"
publicCertArn: ""
services:
  api:
    image:
      tag: "2.0"
    bedrockModelId: "anthropic.claude-3-sonnet-20240229-v1:0"