tenantId: "test-tenant-1123"

publicCertArn: "arn:aws:acm:us-west-2:835316199016:certificate/f7c5d3b0-fcde-43b2-8124-1be55d5ceae2"

services:
  api:
    image:
      tag: "1.0" # show override behavior
    bedrockModelId: "anthropic.claude-3-sonnet-20240229-v1:0"